services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\Objects\MapObjectRepository:

    App\Objects\ImportMapObjects:
        tags: ['console.command']
        arguments:
            $connection: '@doctrine.dbal.dospav_connection'

    App\Objects\ObjectsApiController:
        tags: ['controller.service_arguments']

    App\Objects\ImportCategories:
        tags: ['console.command']
        arguments:
            $sourceConnection: '@doctrine.dbal.dospav_connection'

    App\Objects\CategoriesController:
        tags: ['controller.service_arguments']

    App\Objects\Adding\AddingRequestRepository:

    App\Objects\Adding\AddingController:
        tags: ['controller.service_arguments']

    App\Objects\Adding\AdminController:
        tags: ['controller.service_arguments']