kind: pipeline
type: docker
name: stage

steps:
  - name: deploy
    image: docker/compose:1.24.0
    commands:
      - cd docker
      - docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d --build
    environment:
      COMPOSE_PROJECT_NAME: doskaz
      APP_HOST: doskaz.vps3.zed.kz
      FIREBASE_API_KEY:
        from_secret: firebase_api_key
      DB_NAME: doskaz
      DB_PASSWORD:
        from_secret: db_password
      SENTRY_DSN:
        from_secret: sentry_dsn
      OAUTH_GOOGLE_CLIENT_ID:
        from_secret: oauth_google_client_id
      OAUTH_GOOGLE_CLIENT_SECRET:
        from_secret: oauth_google_client_secret
      OAUTH_GOOGLE_REDIRECT_URI:
        from_secret: oauth_google_redirect_uri
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock

volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock

node:
  server: test