services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\Blog\SlugFactory:

    App\Blog\Categories\CategoryRepository:

    App\Blog\Categories\CategoriesController:
        tags: ['controller.service_arguments']

    App\Blog\Categories\ImportCategories:
        tags: ['console.command']
        arguments:
            $source: '@doctrine.dbal.dospav_connection'

    App\Blog\Posts\PostRepository:

    App\Blog\Posts\PostsController:
        tags: ['controller.service_arguments']

    App\Blog\Posts\ImportBlogPosts:
        tags: ['console.command']
        arguments:
            $source: '@doctrine.dbal.dospav_connection'

    App\Blog\Posts\PostsFinder:

    App\Blog\Comments\CommentRepository:

    App\Blog\Comments\CommentController:
        tags: ['controller.service_arguments']

    App\Blog\Posts\PostsAdminController:
        tags: ['controller.service_arguments']

    App\Blog\Categories\CategoriesAdminController:
        tags: ['controller.service_arguments']