imports:
    - { resource: './CommentsHistory/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\Users\UserRepository:

    League\OAuth2\Client\Provider\Google:
        lazy: true
        arguments:
            - {clientId: '%env(OAUTH_GOOGLE_CLIENT_ID)%', clientSecret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%', redirectUri: '%env(resolve:OAUTH_GOOGLE_REDIRECT_URI)%'}
        tags:
            - {name: 'oauth.provider', key: 'google'}

    App\Users\Security\Oauth\OauthController:
        tags: [ 'controller.service_arguments' ]
        arguments:
            - !tagged_locator { tag: 'oauth.provider', index_by: 'key' }

    App\Users\UserController:
        tags: [ 'controller.service_arguments' ]

    App\Users\Security\AccessTokenRepository:
    App\Users\Security\UserAuthenticator:
    App\Users\Security\Oauth\OauthCredentialsRepository:
    App\Users\Security\AccessTokenAuthenticator:
    App\Users\Security\PhoneAuth\AuthController:
        lazy: true
        arguments:
            - '%env(FIREBASE_API_KEY)%'
        tags: [ 'controller.service_arguments' ]
    App\Users\Security\PhoneAuth\CredentialsRepository:
    App\Users\Security\AuthController:
        tags: [ 'controller.service_arguments' ]

    App\Users\MigrateFullName:
        tags: ['console.command']

    App\Users\Security\UloginAuthenticate:
        tags: ['controller.service_arguments']