version: "3.4"


services:
  backend:
    restart: unless-stopped
    environment:
      - SENTRY_DSN
      - TRUSTED_PROXIES=172.21.0.3/8

  backend_nginx:
    restart: unless-stopped
    networks:
      default:
        aliases:
          - 'doskaz.kz'

  frontend:
    restart: unless-stopped

  database:
    restart: unless-stopped

  imgproxy:
    restart: unless-stopped

  adminpanel:
    restart: unless-stopped

  gotenberg:
    restart: unless-stopped
