version: "3.4"


services:
  backend:
    restart: unless-stopped
    environment:
      - SENTRY_DSN
      - TRUSTED_PROXIES=172.21.0.3/8

  backend_nginx:
    restart: unless-stopped
    networks:
      default:
        aliases:
          - 'doskaz.kz'

  frontend:
    restart: unless-stopped
    environment:
      - ROBOTS_ALLOW=true

  database:
    restart: unless-stopped

  imgproxy:
    restart: unless-stopped

  adminpanel:
    restart: unless-stopped

  gotenberg:
    restart: unless-stopped

  geoip_updater:
    restart: unless-stopped

  rabbitmq:
    restart: unless-stopped

  pgbackups:
    image: prodrigestivill/postgres-backup-local:11-alpine
    depends_on:
      - database
    volumes:
      - pgbackups_data:/backups
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
      - POSTGRES_EXTRA_OPTS=-Z9
    restart: unless-stopped

volumes:
  pgbackups_data:
    driver: local