version: "3.4"


services:
  backend:
    restart: unless-stopped
    environment:
      - SENTRY_DSN
      - TRUSTED_PROXIES=172.25.0.0/16

  backend_nginx:
    restart: unless-stopped
    labels:
      - traefik.http.routers.doskaz_app.tls=true
      - traefik.http.routers.doskaz_app.entrypoints=websecure
      - traefik.http.routers.doskaz_app.tls.certresolver=le
      - traefik.http.routers.app_rss.tls=true
      - traefik.http.routers.app_rss.tls.certresolver=le

  frontend:
    labels:
      - traefik.http.routers.doskaz_frontend_insecure.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.doskaz_frontend_insecure.entrypoints=web
      - traefik.http.routers.doskaz_frontend.tls=true
      - traefik.http.routers.doskaz_frontend.entrypoints=websecure
      - traefik.http.routers.doskaz_frontend.tls.certresolver=le
    restart: unless-stopped

  database:
    restart: unless-stopped

  imgproxy:
    restart: unless-stopped
    labels:
      - traefik.http.routers.doskaz_imgproxy.tls=true
      - traefik.http.routers.doskaz_imgproxy.entrypoints=websecure
      - traefik.http.routers.doskaz_imgproxy.tls.certresolver=le

  adminpanel:
    restart: unless-stopped
    labels:
      - traefik.http.routers.doskaz_adminpanel.tls=true
      - traefik.http.routers.doskaz_adminpanel.entrypoints=websecure
      - traefik.http.routers.doskaz_adminpanel.tls.certresolver=le

  gotenberg:
    restart: unless-stopped
