version: "3.4"


services:
  backend:
    restart: unless-stopped
    environment:
      - SENTRY_DSN

  frontend:
    restart: unless-stopped

  database:
    restart: unless-stopped

  imaginary:
    restart: unless-stopped

  adminpanel:
    restart: unless-stopped
