version: "3.4"

services:
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    environment:
      - FIREBASE_API_KEY
      - DATABASE_URL=pgsql://postgres:${DB_PASSWORD}@database:5432/${DB_NAME}
      - OAUTH_GOOGLE_CLIENT_ID
      - OAUTH_GOOGLE_CLIENT_SECRET
      - OAUTH_GOOGLE_REDIRECT_URI
      - PHP_DATE_TIMEZONE=Asia/Almaty
    volumes:
      - doskaz_storage:/app/public/storage
      - doskaz_storage:/app/storage
    networks:
      - default
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.doskaz_app.rule=Host(`${APP_HOST}`) && PathPrefix(`/api`, `/storage`, `/static`)
      - traefik.http.middlewares.doskaz_compress_app.compress=true
      - traefik.http.routers.doskaz_app.middlewares=doskaz_compress_app
      - traefik.http.routers.app_rss.rule=Host(`${APP_HOST}`) && Path(`/blog/rss`)
      - traefik.http.middlewares.rss_replace.replacepath.path=/api/blogPosts/rss
      - traefik.http.routers.app_rss.middlewares=rss_replace
    depends_on:
      - database

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        firebase_api_key: ${FIREBASE_API_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.doskaz_frontend.rule=Host(`${APP_HOST}`)
      - traefik.http.middlewares.doskaz_compress_frontend.compress=true
      - traefik.http.routers.doskaz_frontend.middlewares=doskaz_compress_frontend
      - traefik.port=3000
    networks:
      - web
    environment:
      - BACKEND_DOMAIN=http://backend
      - NUXT_HOST=0.0.0.0
    depends_on:
      - backend

  adminpanel:
    build:
      context: ../adminpanel
      dockerfile: Dockerfile
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.doskaz_adminpanel.rule=Host(`${APP_HOST}`) && PathPrefix(`/adminpanel`)
      - traefik.http.routers.doskaz_adminpanel.middlewares=doskaz_compress_frontend
    depends_on:
      - backend

  database:
    image: mdillon/postgis:11
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - doskaz_db:/var/lib/postgresql/data

  imaginary:
    image: h2non/imaginary
    volumes:
      - doskaz_storage:/mnt/data/storage
    command: -mount /mnt/data -http-cache-ttl 31536000 -concurrency 20 -cpus 4
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.docker.network=web
      - traefik.http.routers.doskaz_imaginary.rule=Host(`${APP_HOST}`) && PathPrefix(`/image`, `/pipeline`)
      - traefik.http.middlewares.doskaz_imaginary.stripprefix.prefixes=/image
      - traefik.http.routers.doskaz_imaginary.middlewares=doskaz_imaginary

  gotenberg:
    image: thecodingmachine/gotenberg:6

volumes:
  doskaz_db:
    external: true
  doskaz_storage:
    external: true

networks:
  web:
    external: true