services:
  _defaults:
    autowire: true
    autoconfigure: false

  App\Objects\PhotosAdding\Controller\PhotosAddingController:
    tags: [ 'controller.service_arguments' ]

  App\Objects\PhotosAdding\Repository\PhotosAddingRequestRepository: