services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\Complaints\ComplaintController:
        tags: ['controller.service_arguments']

    App\Complaints\ComplaintRepository: