imports:
    - { resource: './DomainEvents/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: false

    App\Infrastructure\Api\KernelExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -127 }
        arguments:
            $isDebug: '%kernel.debug%'

    App\Infrastructure\Api\ExceptionNormalizer:
        arguments:
            - '%kernel.debug%'
        tags:
            - { name: serializer.normalizer, priority: 7 }

    App\Infrastructure\Api\HttpExceptionNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 8 }

    App\Infrastructure\Api\SerializerExceptionNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 8 }

    App\Infrastructure\ObjectResolver\ValidationExceptionNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 8 }

    App\Infrastructure\Doctrine\Flusher:

    App\Infrastructure\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber}

    App\Infrastructure\Api\ResponseViewListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: -1}

    App\Infrastructure\ObjectResolver\ObjectArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: -49 }

    Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    League\Flysystem\Adapter\Local:
        arguments:
            - '%kernel.project_dir%/storage'

    App\Infrastructure\Storage\StorageController:
        tags: ['controller.service_arguments']
        arguments:
            - '@League\Flysystem\Adapter\Local'

    App\Infrastructure\Api\DocumentationController:
        tags: ['controller.service_arguments']
        arguments:
            - '%kernel.project_dir%/src'

    App\Infrastructure\AttributeNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 1 }

    App\Infrastructure\FileNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 1 }

    Imgproxy\UrlBuilder:
        arguments:
            - '/img'