users:
    resource: ../../src/Users
    type: annotation

objects:
    resource: ../../src/Objects
    type: annotation

blog:
    resource: ../../src/Blog
    type: annotation

storage:
    resource: ../../src/Infrastructure/Storage
    type: annotation

complaints:
    resource: ../../src/Complaints
    type: annotation

cities:
    resource: ../../src/Cities
    type: annotation

apiDocs:
    resource: ../../src/Infrastructure/Api
    type: annotation
