services:
  _defaults:
    autowire: true
    autoconfigure: false

  App\RegionalCoordinators\RegionalCoordinatorController:
    tags: ['controller.service_arguments']

  App\RegionalCoordinators\RegionalCoordinatorRepository: